language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: r6J92JdfGPUSkEiw1x0M3Astyf2z9lCMNRwhqYCYbGJjD3iAL1TKUOJ5CybRgIRV2oRW+MeXHAki309LkuYjltEimNqWMzo9tPOeLFmjyqGbvxRdd3qvhtTuU/SHMyHSxdztNtcnZsUkA9j9FWYWq+3Cj4zeJXWuEuHb4TQb2bfmoJ2jH/zOki+nK6YHPv5yl++xrrv1F626lNo4seTMPAVrZDIA2p5vk9FQIGGF2GPJKsE2JijWyCHLUMt5+xGhA9jpmm6vcq1Dc4+m/CoJHk84NrPDcf8Oogl/4QubLO8cyZ4l8YggdlYG87mwSY6VwQPFMo8L+6qFG77KhiDfD1cu7Xrvymk9i94sirwib7OOsmAAEx08eLSJl+LlPM6jIexkqlNMb080LU4K4yo40Q4oRwmkrIzlyNJ5qXzNCIe/PqmSqDOzMiHrjCdO+aQZFqn7yhmSwz5hjejjvskxdoc6Tvlt8WFT4q6VRCOcCcRD7Yw1EiywWYmHYW7Eem78alVa9aCTcsu0H48TukBMjcbdESNcw3LjLWSGMCHICXb7WPFgNczQIpZuO11mowxt09t4lm61/JGhbenVxITY6i+Wn52WbY9dXoetz+rwrY2YOJ+ausS0Lsmq+bJhnJ6fdlx1dMt0zlmxuU5C0YespPFh9+bXT/eIkaXFYEL+YLU=
